### PR TITLE
Align api header

### PR DESCRIPTION
**Pull request by dvdvideo1234**

### CODE REVIEW

**Comment by dvdvideo1234** [comment]
Hey, @shadowscion ;)

Please merge as you do not have to support:
https://github.com/shadowscion/shadowscion

I already have these here and they will persists for for a long time 
https://github.com/dvdvideo1234/ZeroBraineProjects/tree/master/ExtractWireWiki/types

**Comment by shadowscion** [comment]
I did it on purpose I don't want to link to external stuff

Tell me what I need to add

**Comment by dvdvideo1234** [comment]
Hi,

Only maybe that `100% Clientside (apart from the networked editable options); no more laggy e2 tracks, or, god forbid, physical ones!` is quite long. Could you change it. I will close the PR now ;)

**Comment by dvdvideo1234** [comment]
* 100% Clientside (apart from the networked editable options)
* No more laggy `E2` tracks, or, god forbid, physical ones!

**Comment by shadowscion** [comment]
I could probably just remove the second statement... I haven't seen e2 tracks in 10 years and I've literally never seen physical ones lol.

**Pull request closed without merging**
